title = "Pack A: Starting Out"
slug = "pack-a"
description = "Simple levels to learn the rules of Sokoban."
author = "Brett Chalupa"
license = "CC0 (Public Domain)"
difficulty = "Easy"
year = 2024
version = "0.1"

[[levels]]
title = "Level 1"
data = '''
#####
#@$.#
#####
'''

[[levels]]
title = "Level 2"
data = '''
######
#    #
#    #
#@$#.#
#    #
######
'''

[[levels]]
title = "Level 3"
data = '''
#######
#-----#
#@$$.-#
#--.--#
#######
'''

[[levels]]
title = "Level 4"
data = '''
#######
#     #
#     #
#@$$. #
## .  #
#######
'''

[[levels]]
title = "Level 5"
data = '''
########
#.#.#.##
#      #
# # #  #
# $$$  #
#     @#
########
'''

[[levels]]
title = "Level 6"
data = '''
#######
##    #
# $.  #
# $ # #
#@$   #
##..  #
#######
'''

[[levels]]
title = "Level 7"
data = '''
########
#      #
#@     #
##$$##.#
#     .#
########
'''

[[levels]]
title = "Level 8"
data = '''
########
#      #
#@ $  .#
##$$##.#
#     .#
########
'''

[[levels]]
title = "Level 9"
data = '''
#######
#  #  #
#@ #  #
#  $  #
# $# ###
#    ..#
########
'''

[[levels]]
title = "Level 10"
data = '''
#########
#      #.#
#  $    .#
# $$#   .#
# @     ##
#########
'''

[[levels]]
title = "Level 11"
data = '''
#######
##     #
#  $   ##
# $ #  ..#
#@$$   ..#
##     ##
########
'''

[[levels]]
title = "Level 12"
data = '''
##########
##    ..##
#  $ #.. #
# $ @##  #
# $      #
#  $     #
##      ##
##########
'''

[[levels]]
title = "Level 13"
data = '''
#########
# .##   #
#   #@$ #
#     $ #
# .##   #
#########
'''

[[levels]]
title = "Level 14"
data = '''
#########
#       #
#     $ #
# .## $ #
# .# @$ #
# .   $ #
# .##   #
#########
'''

[[levels]]
title = "Level 15"
data = '''
############
#          #
#@         #
# $$#    $ #
#   #    ##
#######...#
       ####
'''

[[levels]]
title = "Level 16"
data = '''
###################
#                 #
#@                #
# $$#    $    #$$ #
#   #    ##   #   #
#######.....#######
       #####
'''

[[levels]]
title = "Level 17"
data = '''
##########
#        #
#@$ $  $ #
#   #  # #
##### ####
   #.   #
   #.  .#
   ##  ##
    ####
'''

[[levels]]
title = "Level 18"
data = '''
#####
#.  ####
##$    #
# .$ @ #
# . $# #
###    #
  ######
'''

[[levels]]
title = "Level 19"
data = '''
#######
##    #
#  $  #
# $ # #
#@$$  #
##....#
#######
'''

[[levels]]
title = "Level 20"
data = '''
##########
#        #
#  $$ $$ #
#@$$   $ #
#  ## ## #
## #   ###
 # . $ #
 #.#...#
 ###...#
   #####
'''
